repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: terraform-validate
  - id: terraform-fmt
  - id: tflint
    args:
      # - "--module"
      - "--config=./.tflint.d/.tflint.hcl"
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-go
      args: ["markdown", "table", "--output-file", "README.md", "./"]