name: 'Terraform'

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache plugin dir
      uses: actions/cache@v2
      with:
        path: ~/.tflint.d/plugins
        key: .tflint.hcl

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
        
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
      
    - name: Init TFLint
      run: tflint --init -c ./.tflint.d/.tflint.hcl

    - name: Init Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Check formatting
      run: terraform fmt -check
      
    - name: Run TFLint
      run: tflint -f compact -c ./.tflint.d/.tflint.hcl
